language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: QeNaYZ2a8+rBAqzOdF7vY2btaCECa8/r+gCxCVfYa+r/Kr5S25MQeTrdGOf6/3a4S4GZMp/0okiLAyrZqdOdU33QEi6vkfWK7ntskiMM/wH6CCSHpxu9raOR0U2TobsTiWf5B0UThrxVNQwwsuVbUcqVJApF44SHOpd11JUGne2juaEcWZ7CVHQ2Q3HfX4Kz/OMjRZOZ5WeeH6n/NdsFhCjTVbO0ygi7cnG6dSyvYlOlfgp6WlpWpJH9bQ6aalV3Yv8INY2DJiLugaWfS+aM+B8n3UkmvotnyveBeGgACoAUEKzmhfSzWn6ab2COMzHBkzPLMe83p2iB6/+QnsG7mH31cu/f9b+RxRYLvVap93DvSKNycGiFO5MAqfGYzOXyP1aWBhlA1kVnAPRVbWRs69PtWYWM2BebZpwL9vtYorLUp5Cu+q+Pxc//4BpKgMVY7usx6g9r4AbWuWAj5AwZWbWyIqO3Hvntrabm+SpgRFmbXy3xY0V7LvaaZha71WL3LivLY0k54dWmBdZyqAnMLmscTaB4FLzE3IwRlFCjsVUk4Phpg8/2nnD3qy0nwgzlatkO8vgIEw+seYjum2UlEuitFeYSkBJvBoVyCP97CFc73dcN2fXF9PhDkts4beJVZaQTSggll7faEcaHxu3NEvasob3dvH8Ia+speAEjEso=
  on:
    tags: true
    repo: tcdl/json-masker
    node: '7'
