language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: NxdgAxRfGd66W7Owoevm8PI2fCZX8Nrg4YjGyg64WODTnaNSJ/NsuAwjcGXJbkO1etG/fyE3g4ENYpf5jHWGowVHX/gRSeJRV/NFlEvZm4lUcalFAhImKQcb2zaH3mKMUS9jyKhCYQWh1e9Kx2XNvWwM1KyOWWkOg8nCsFGMpfCiu6sJlctkIDZQkJFGw+cZVQlYYOvpm/O1DBKhB2ihs4ubECwUNqn+8Qpvw3n3H9r//47csDonziGaTcrRLGxuo82db4gSOGe3RYgWkOhuKvOdaSQaVCA1JhVbJyv7LXvLqegKQtj5GinJVPS5u89yDO68PkRdnJwIKNhCQ9G3JclQX2GOrR3vvXJyEueNvCDXYPrFXZs37kws41L7YDNb/qHbZd8olRoWUJe6czSpFNOSTHMcCoACmz7x7zAwHpurjgnV0HxImbAOkR0IcJDNhLM8aLggNWC26aRbgHN0pJyNcKoUD1BH0cJafUp2pTjg7klRerNPnfeGDuDMGZV1bnv7K+2awKgAKhh7i6EDqkHi/ARSMwbYMqHPvw1ODY0TY59ySOpb6XvrLbJ+eWgv1TAlb2PdWEIjKD839BscCaDXX9qZtYo3JexmS0WUriPVReCZCTwyoFSmSezDoPnFKQZXI9deImu8SRPabCms0rf2bcS5cw1apgQwOkXmG34=
  on:
    tags: true
    repo: tcdl/json-masker
    node: '7'
